project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://github.com/SL-sora/STA9750-2026-FALL/"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: "./index.html"
      - text: "Projects"
        href: "./project_experience.html"
      - text: "Experience"
        href: "./professional_experience.html"
      - text: "Contact"
        href: "./contact_information.html"
    
format:
  html:
    theme: vapor
    toc: false

editor:
  mode: source